# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x08protobuf\x1a\x1bgoogle/protobuf/empty.proto\"?\n\x0c\x46ullUserData\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.protobuf.User\x12\x11\n\tSessionID\x18\x02 \x01(\t\" \n\x0bSessionData\x12\x11\n\tSessionID\x18\x01 \x01(\t\"1\n\x04User\x12\n\n\x02ID\x18\x01 \x01(\r\x12\r\n\x05\x45mail\x18\x02 \x01(\t\x12\x0e\n\x06IsAuth\x18\x04 \x01(\x08\x32\xb9\x01\n\x04\x41uth\x12?\n\rCreateSession\x12\x16.protobuf.FullUserData\x1a\x16.google.protobuf.Empty\x12\x37\n\x0eGetCurrentUser\x12\x15.protobuf.SessionData\x1a\x0e.protobuf.User\x12\x37\n\x06Logout\x12\x15.protobuf.SessionData\x1a\x16.google.protobuf.EmptyB\x0eZ\x0c\x65xample/authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014example/auth'
  _globals['_FULLUSERDATA']._serialized_start=53
  _globals['_FULLUSERDATA']._serialized_end=116
  _globals['_SESSIONDATA']._serialized_start=118
  _globals['_SESSIONDATA']._serialized_end=150
  _globals['_USER']._serialized_start=152
  _globals['_USER']._serialized_end=201
  _globals['_AUTH']._serialized_start=204
  _globals['_AUTH']._serialized_end=389
# @@protoc_insertion_point(module_scope)
