# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDirectory = channel.unary_unary(
                '/catalog.CatalogService/CreateDirectory',
                request_serializer=catalog__pb2.CreateDirectoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.DirectoryResponse.FromString,
                _registered_method=True)
        self.UpdateDirectory = channel.unary_unary(
                '/catalog.CatalogService/UpdateDirectory',
                request_serializer=catalog__pb2.UpdateDirectoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.DirectoryResponse.FromString,
                _registered_method=True)
        self.DeleteDirectory = channel.unary_unary(
                '/catalog.CatalogService/DeleteDirectory',
                request_serializer=catalog__pb2.DeleteDirectoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetDirectoryContent = channel.unary_unary(
                '/catalog.CatalogService/GetDirectoryContent',
                request_serializer=catalog__pb2.GetDirectoryRequest.SerializeToString,
                response_deserializer=catalog__pb2.DirectoryContentResponse.FromString,
                _registered_method=True)
        self.RegisterFile = channel.unary_unary(
                '/catalog.CatalogService/RegisterFile',
                request_serializer=catalog__pb2.RegisterFileRequest.SerializeToString,
                response_deserializer=catalog__pb2.FileResponse.FromString,
                _registered_method=True)
        self.UpdateFile = channel.unary_unary(
                '/catalog.CatalogService/UpdateFile',
                request_serializer=catalog__pb2.UpdateFileRequest.SerializeToString,
                response_deserializer=catalog__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/catalog.CatalogService/DeleteFile',
                request_serializer=catalog__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=catalog__pb2.DeleteResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDirectoryContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectory,
                    request_deserializer=catalog__pb2.CreateDirectoryRequest.FromString,
                    response_serializer=catalog__pb2.DirectoryResponse.SerializeToString,
            ),
            'UpdateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDirectory,
                    request_deserializer=catalog__pb2.UpdateDirectoryRequest.FromString,
                    response_serializer=catalog__pb2.DirectoryResponse.SerializeToString,
            ),
            'DeleteDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDirectory,
                    request_deserializer=catalog__pb2.DeleteDirectoryRequest.FromString,
                    response_serializer=catalog__pb2.DeleteResponse.SerializeToString,
            ),
            'GetDirectoryContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirectoryContent,
                    request_deserializer=catalog__pb2.GetDirectoryRequest.FromString,
                    response_serializer=catalog__pb2.DirectoryContentResponse.SerializeToString,
            ),
            'RegisterFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFile,
                    request_deserializer=catalog__pb2.RegisterFileRequest.FromString,
                    response_serializer=catalog__pb2.FileResponse.SerializeToString,
            ),
            'UpdateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFile,
                    request_deserializer=catalog__pb2.UpdateFileRequest.FromString,
                    response_serializer=catalog__pb2.FileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=catalog__pb2.DeleteFileRequest.FromString,
                    response_serializer=catalog__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/CreateDirectory',
            catalog__pb2.CreateDirectoryRequest.SerializeToString,
            catalog__pb2.DirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/UpdateDirectory',
            catalog__pb2.UpdateDirectoryRequest.SerializeToString,
            catalog__pb2.DirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/DeleteDirectory',
            catalog__pb2.DeleteDirectoryRequest.SerializeToString,
            catalog__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDirectoryContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/GetDirectoryContent',
            catalog__pb2.GetDirectoryRequest.SerializeToString,
            catalog__pb2.DirectoryContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/RegisterFile',
            catalog__pb2.RegisterFileRequest.SerializeToString,
            catalog__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/UpdateFile',
            catalog__pb2.UpdateFileRequest.SerializeToString,
            catalog__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.CatalogService/DeleteFile',
            catalog__pb2.DeleteFileRequest.SerializeToString,
            catalog__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
