# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x08protobuf\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x11\x44\x65leteFileRequest\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x0e\n\x06UserID\x18\x02 \x01(\r2I\n\x04\x46ile\x12\x41\n\nDeleteFile\x12\x1b.protobuf.DeleteFileRequest\x1a\x16.google.protobuf.EmptyB\x02Z\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\000'
  _globals['_DELETEFILEREQUEST']._serialized_start=53
  _globals['_DELETEFILEREQUEST']._serialized_end=102
  _globals['_FILE']._serialized_start=104
  _globals['_FILE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
